# Generated by Django 3.2 on 2021-04-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_api', '0002_teachingsession'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teachingsession',
            constraint=models.UniqueConstraint(fields=('username', 'lesson_id'), name='unique_sign_in'),
        ),
    ]
